# Generated by Django 5.2.4 on 2025-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('boys', 'Boys Wear'), ('girls', 'Girls Wear')], default='boys', max_length=10),
        ),
    ]
